server:
  port: 9090
  context-path: /app-admin-server
spring:
  application:
    name: app-admin-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    data-username: root
    data-password: 123456
    tomcat:
      max-wait: 10000
      validation-query: select 1
      max-idle: 10
      min-idle: 5
      initial-size: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml





